name: Publish
on: [push]
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@wings-software"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_HARNESS_BOT_TOKEN }}
      - name: Test
        run: |
          npm install
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com/ > ~/.npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_HARNESS_BOT_TOKEN }}$ >> ~/.npmrc
          echo always-auth=true >> ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_HARNESS_BOT_TOKEN }}$