name: Test, Build, and Publish
on: [push]
jobs:
  build:
    name: Test, Build, and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@wings-software"
      - name: Test
        run: |
          npm install
          npm run test
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: |
          echo @wings-software:registry=https://npm.pkg.github.com > ~/.npmrc
          echo //npm.pkg.github.com/:_authToken=6757cd18bb54ab86e290fdfc255c4443dd7fb453 >> ~/.npmrc
          echo always-auth=true  >> ~/.npmrc
          cat ~/.npmrc
          npm publish
