name: Publish
on: [push]
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test, Build, and Publish
        run: |
          npm install
          npm run test
          npm run build
